// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import ()

type Iten struct {
	ID     int32
	Name   string
	UserID int32
}

type User struct {
	ID   int32
	Name string
}
